-- MySQL Script generated by MySQL Workbench
-- Mon Sep 14 17:06:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema food_delivery_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_delivery_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_delivery_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `food_delivery_db` ;

-- -----------------------------------------------------
-- Table `food_delivery_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`user` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Role` ENUM('Customer', 'Restaurant', 'Driver', 'Admin') NOT NULL,
  `Address` TEXT NULL DEFAULT NULL,
  `CreatedAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Phone` (`Phone` ASC) VISIBLE,
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`address` (
  `AddressID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `Label` VARCHAR(50) NULL DEFAULT NULL,
  `RecipientName` VARCHAR(100) NOT NULL,
  `RecipientPhone` VARCHAR(20) NOT NULL,
  `AddressLine` TEXT NOT NULL,
  `Ward` VARCHAR(100) NULL DEFAULT NULL,
  `District` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(100) NULL DEFAULT NULL,
  `Latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `Longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `IsDefault` TINYINT(1) NOT NULL,
  PRIMARY KEY (`AddressID`),
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `address_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `food_delivery_db`.`user` (`UserID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `LoyaltyPoints` INT NULL DEFAULT NULL,
  `TotalOrders` INT NULL DEFAULT NULL,
  `PreferredPayment` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CustomerID`),
  UNIQUE INDEX `UserID` (`UserID` ASC) VISIBLE,
  CONSTRAINT `customer_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `food_delivery_db`.`user` (`UserID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`hub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`hub` (
  `HubID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Location` VARCHAR(255) NOT NULL,
  `ManagerID` INT NULL DEFAULT NULL,
  `OperatingArea` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`HubID`),
  INDEX `ManagerID` (`ManagerID` ASC) VISIBLE,
  CONSTRAINT `hub_ibfk_1`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `food_delivery_db`.`user` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`restaurant` (
  `RestaurantID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `BusinessLicense` VARCHAR(50) NULL DEFAULT NULL,
  `CuisineType` VARCHAR(100) NULL DEFAULT NULL,
  `OpeningHours` VARCHAR(100) NULL DEFAULT NULL,
  `CommissionRate` DECIMAL(5,2) NULL DEFAULT NULL,
  `HubID` INT NULL DEFAULT NULL,
  `IsApproved` TINYINT(1) NOT NULL,
  `IsOpen` TINYINT(1) NOT NULL,
  `MinOrderAmount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`RestaurantID`),
  UNIQUE INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `HubID` (`HubID` ASC) VISIBLE,
  CONSTRAINT `restaurant_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `food_delivery_db`.`user` (`UserID`),
  CONSTRAINT `restaurant_ibfk_2`
    FOREIGN KEY (`HubID`)
    REFERENCES `food_delivery_db`.`hub` (`HubID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`driver` (
  `DriverID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `DriverLicense` VARCHAR(50) NULL DEFAULT NULL,
  `VehicleType` VARCHAR(50) NULL DEFAULT NULL,
  `PlateNumber` VARCHAR(20) NULL DEFAULT NULL,
  `CurrentLocation` VARCHAR(255) NULL DEFAULT NULL,
  `Status` ENUM('ONLINE', 'OFFLINE', 'BUSY') NULL DEFAULT NULL,
  `HubID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`DriverID`),
  UNIQUE INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `HubID` (`HubID` ASC) VISIBLE,
  CONSTRAINT `driver_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `food_delivery_db`.`user` (`UserID`),
  CONSTRAINT `driver_ibfk_2`
    FOREIGN KEY (`HubID`)
    REFERENCES `food_delivery_db`.`hub` (`HubID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `CustomerID` INT NOT NULL,
  `RestaurantID` INT NOT NULL,
  `DriverID` INT NULL DEFAULT NULL,
  `OrderDate` DATETIME NULL DEFAULT now(),
  `TotalAmount` DECIMAL(10,2) NOT NULL,
  `Status` ENUM('PENDING', 'CONFIRMED', 'PREPARING', 'READY', 'PICKED_UP', 'DELIVERING', 'COMPLETED', 'CANCELLED') NULL DEFAULT NULL,
  `DeliveryFee` DECIMAL(10,2) NULL DEFAULT NULL,
  `Discount` DECIMAL(10,2) NULL DEFAULT NULL,
  `PaymentMethod` VARCHAR(50) NULL DEFAULT NULL,
  `DeliveryAddressSnapshot` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `CustomerID` (`CustomerID` ASC) VISIBLE,
  INDEX `RestaurantID` (`RestaurantID` ASC) VISIBLE,
  INDEX `DriverID` (`DriverID` ASC) VISIBLE,
  CONSTRAINT `order_ibfk_1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `food_delivery_db`.`customer` (`CustomerID`),
  CONSTRAINT `order_ibfk_2`
    FOREIGN KEY (`RestaurantID`)
    REFERENCES `food_delivery_db`.`restaurant` (`RestaurantID`),
  CONSTRAINT `order_ibfk_3`
    FOREIGN KEY (`DriverID`)
    REFERENCES `food_delivery_db`.`driver` (`DriverID`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`auditlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`auditlog` (
  `LogID` INT NOT NULL AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `OldStatus` VARCHAR(50) NULL DEFAULT NULL,
  `NewStatus` VARCHAR(50) NOT NULL,
  `ChangedBy` INT NOT NULL,
  `ChangedAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`LogID`),
  INDEX `OrderID` (`OrderID` ASC) VISIBLE,
  INDEX `ChangedBy` (`ChangedBy` ASC) VISIBLE,
  CONSTRAINT `auditlog_ibfk_1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `food_delivery_db`.`order` (`OrderID`),
  CONSTRAINT `auditlog_ibfk_2`
    FOREIGN KEY (`ChangedBy`)
    REFERENCES `food_delivery_db`.`user` (`UserID`))
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`cart` (
  `CartID` INT NOT NULL AUTO_INCREMENT,
  `CustomerID` INT NOT NULL,
  `RestaurantID` INT NULL DEFAULT NULL,
  `UpdatedAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`CartID`),
  UNIQUE INDEX `CustomerID` (`CustomerID` ASC) VISIBLE,
  INDEX `RestaurantID` (`RestaurantID` ASC) VISIBLE,
  CONSTRAINT `cart_ibfk_1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `food_delivery_db`.`customer` (`CustomerID`)
    ON DELETE CASCADE,
  CONSTRAINT `cart_ibfk_2`
    FOREIGN KEY (`RestaurantID`)
    REFERENCES `food_delivery_db`.`restaurant` (`RestaurantID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`menuitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`menuitem` (
  `MenuItemID` INT NOT NULL AUTO_INCREMENT,
  `RestaurantID` INT NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Category` VARCHAR(50) NULL DEFAULT NULL,
  `IsAvailable` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`MenuItemID`),
  INDEX `RestaurantID` (`RestaurantID` ASC) VISIBLE,
  CONSTRAINT `menuitem_ibfk_1`
    FOREIGN KEY (`RestaurantID`)
    REFERENCES `food_delivery_db`.`restaurant` (`RestaurantID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`cartitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`cartitem` (
  `CartItemID` INT NOT NULL AUTO_INCREMENT,
  `CartID` INT NOT NULL,
  `MenuItemID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`CartItemID`),
  UNIQUE INDEX `uq_cart_item` (`CartID` ASC, `MenuItemID` ASC) VISIBLE,
  INDEX `MenuItemID` (`MenuItemID` ASC) VISIBLE,
  CONSTRAINT `cartitem_ibfk_1`
    FOREIGN KEY (`CartID`)
    REFERENCES `food_delivery_db`.`cart` (`CartID`)
    ON DELETE CASCADE,
  CONSTRAINT `cartitem_ibfk_2`
    FOREIGN KEY (`MenuItemID`)
    REFERENCES `food_delivery_db`.`menuitem` (`MenuItemID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`coupon` (
  `CouponID` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(50) NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `CouponType` ENUM('PERCENT', 'FIXED') NOT NULL,
  `Value` DECIMAL(10,2) NOT NULL,
  `MinOrderAmount` DECIMAL(10,2) NOT NULL,
  `MaxDiscount` DECIMAL(10,2) NULL DEFAULT NULL,
  `UsageLimit` INT NULL DEFAULT NULL,
  `UsedCount` INT NOT NULL,
  `StartsAt` DATETIME NOT NULL,
  `ExpiresAt` DATETIME NOT NULL,
  `IsActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`CouponID`),
  UNIQUE INDEX `Code` (`Code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`couponusage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`couponusage` (
  `CouponUsageID` INT NOT NULL AUTO_INCREMENT,
  `CouponID` INT NOT NULL,
  `UserID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  `UsedAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`CouponUsageID`),
  UNIQUE INDEX `uq_coupon_order` (`CouponID` ASC, `OrderID` ASC) VISIBLE,
  INDEX `UserID` (`UserID` ASC) VISIBLE,
  INDEX `OrderID` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `couponusage_ibfk_1`
    FOREIGN KEY (`CouponID`)
    REFERENCES `food_delivery_db`.`coupon` (`CouponID`)
    ON DELETE CASCADE,
  CONSTRAINT `couponusage_ibfk_2`
    FOREIGN KEY (`UserID`)
    REFERENCES `food_delivery_db`.`user` (`UserID`)
    ON DELETE CASCADE,
  CONSTRAINT `couponusage_ibfk_3`
    FOREIGN KEY (`OrderID`)
    REFERENCES `food_delivery_db`.`order` (`OrderID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`notification` (
  `NotificationID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `Type` ENUM('ORDER', 'PROMOTION', 'SYSTEM') NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Message` TEXT NOT NULL,
  `IsRead` TINYINT(1) NOT NULL,
  `CreatedAt` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`NotificationID`),
  INDEX `idx_notification_user_read` (`UserID` ASC, `IsRead` ASC, `CreatedAt` ASC) VISIBLE,
  CONSTRAINT `notification_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `food_delivery_db`.`user` (`UserID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`orderitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`orderitem` (
  `OrderItemID` INT NOT NULL AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `MenuItemID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `ItemName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`OrderItemID`),
  INDEX `OrderID` (`OrderID` ASC) VISIBLE,
  INDEX `MenuItemID` (`MenuItemID` ASC) VISIBLE,
  CONSTRAINT `orderitem_ibfk_1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `food_delivery_db`.`order` (`OrderID`),
  CONSTRAINT `orderitem_ibfk_2`
    FOREIGN KEY (`MenuItemID`)
    REFERENCES `food_delivery_db`.`menuitem` (`MenuItemID`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`payment` (
  `PaymentID` INT NOT NULL AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `Amount` DECIMAL(10,2) NOT NULL,
  `PaymentMethod` VARCHAR(50) NOT NULL,
  `Status` ENUM('PENDING', 'SUCCESS', 'FAILED') NULL DEFAULT NULL,
  `TransactionDate` DATETIME NULL DEFAULT now(),
  `Provider` VARCHAR(50) NULL DEFAULT NULL,
  `ProviderTransactionID` VARCHAR(150) NULL DEFAULT NULL,
  `PaidAt` DATETIME NULL DEFAULT NULL,
  `FailureReason` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`PaymentID`),
  UNIQUE INDEX `ProviderTransactionID` (`ProviderTransactionID` ASC) VISIBLE,
  INDEX `OrderID` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `food_delivery_db`.`order` (`OrderID`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`review` (
  `ReviewID` INT NOT NULL AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `ReviewerID` INT NOT NULL,
  `TargetType` ENUM('Restaurant', 'Driver') NOT NULL,
  `Rating` INT NULL DEFAULT NULL,
  `Comment` TEXT NULL DEFAULT NULL,
  `ReviewDate` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`ReviewID`),
  UNIQUE INDEX `uq_review_order_reviewer_target` (`OrderID` ASC, `ReviewerID` ASC, `TargetType` ASC) VISIBLE,
  INDEX `ReviewerID` (`ReviewerID` ASC) VISIBLE,
  CONSTRAINT `review_ibfk_1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `food_delivery_db`.`order` (`OrderID`),
  CONSTRAINT `review_ibfk_2`
    FOREIGN KEY (`ReviewerID`)
    REFERENCES `food_delivery_db`.`user` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `food_delivery_db`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_delivery_db`.`shift` (
  `ShiftID` INT NOT NULL AUTO_INCREMENT,
  `DriverID` INT NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `EndTime` DATETIME NULL DEFAULT NULL,
  `CompletedOrders` INT NULL DEFAULT NULL,
  `BonusEarned` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ShiftID`),
  INDEX `DriverID` (`DriverID` ASC) VISIBLE,
  CONSTRAINT `shift_ibfk_1`
    FOREIGN KEY (`DriverID`)
    REFERENCES `food_delivery_db`.`driver` (`DriverID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
